### ISSUE TITLE
scannet submit

### ISSUE THREAD

**Issue by prograguo** [wbhu/BPNet#11]
I submitted it according to the format for 3d semantic segmentation. I don't know where the processing occurs. Please tell me what these four files are respectively？
Thanks！！！

********** ********** ********** ********** ********** ********** 
Dear benchmark user,

Unfortunately, our evaluation system failed to evaluate your result submission for ****.
Reason: results folder does not contain 4 subfolders with correct format:

The system thinks that the problem is due to invalid input.
However, if you think it is the system's fault, please contact an administrator.

Best regards,
The ScanNet Benchmark administrators

********** ********** ********** ********** ********** **********

**Comment by wbhu** [comment]
Please check the submission format on the official website.
