### ISSUE TITLE
The problem about the training accuracy of MinkUNet18A 

### ISSUE THREAD

**Issue by Gao-JT** [wbhu/BPNet#13]
First of all, thank you for your wonderful work! Now, I normally try to reproduce the 3D semantic segmentation results of MinkowskiUNet18A in the paper, but it seems that the accuracy can only reach 55%, which is 13% different from the 68% shown in Table 5 in the paper. Is there any problem with the training process?
![1](https://user-images.githubusercontent.com/40292624/138549443-e907f513-0cd4-4d7b-bd37-07dae374f4aa.png)

The following are my experimental parameter settings：
 
![image](https://user-images.githubusercontent.com/40292624/138549658-5f62042c-0376-4d69-ba4a-4907c139fc35.png)

Thank you again for your excellent work and look forward to your reply.
Best regards!

**Comment by ds0529** [comment]
I have the similar problem. I used the provided trained model to evaluate in val set of ScanNet, but the 2D mIoU and 3D mIoU are 64.2 and 64.8 seperately, which are different from the results of 65.1 and 70.6 in the Table 5.

**Comment by ds0529** [comment]
I found that the number of used GPUs greatly affects mIoU on the val set. When I used one GPU to evaluate the provided trained model on the val set of ScanNet, the 3D mIoU is 64.8%. However, when I used two or four GPUs, the 3D mIoU is about 71%.

I also reproduce the 3D semantic segmentation results of MinkowskiUNet18A on ScanNet. I used 2 GPUs to train the MinkowskiUNet18A with other parameters same as BPNet. The 3D mIoU on the val set is 64%, which is different from the result of 68% in the Table 5. When I set the initial learning rate to 0.1, the 3D mIoU on the val set is 67.4%.

**Comment by wbhu** [comment]
Hi @ds0529, @Gao-JT ,

Thanks for your report. The number of GPUs should affect the test result, this is because we test the validation set multiple times to address the problem of the number of voxels being greatly smaller than that of points, and the final accuracy is reported based on points. This evaluation strategy is borrowed from the sparse convolution (https://github.com/facebookresearch/SparseConvNet). If we use 4 GPUs to test the results, the final is aggregated 4 times. So if you are using a single GPU to test the model, please revise the 'test_repeats' value to be 4 times as the original one.

**Comment by pengsongyou** [comment]
Hi @wbhu, thanks a lot for your great work! I have a related question regarding the validation accuracy. I tried to train a MinkUNet18A model from scratch, but the best validation mIoU that I can get is only 63%. I tried what you suggested to change to `test_repeats=4` in the config file, but the result in each iteration in the 4 are almost the same, and the final `accum_miou` is not improved at all. Does improving results only work with multi GPU evaluation?

Then I try to evaluate with 2 GPUs, but the distributed thing seems to give me the following NCCL error. Do you have an idea on why this happened?

```bash
torch.__version__:1.7.1+cu110
torch.version.cuda:11.0
torch.backends.cudnn.version:8005
torch.backends.cudnn.enabled:True
Traceback (most recent call last):
  File "Exp/scannet/mink_noaug/test.py", line 262, in <module>
    main()
  File "Exp/scannet/mink_noaug/test.py", line 107, in main
    mp.spawn(main_worker, nprocs=args.ngpus_per_node, args=(args.ngpus_per_node, args))
  File "/home/songyou/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/songyou/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/songyou/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/songyou/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/songyou/workspace/distill_net/Exp/scannet/mink_noaug/test.py", line 121, in main_worker
    rank=args.rank)
  File "/home/songyou/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/home/songyou/anaconda3/envs/deep_view_aggregation/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:784, invalid usage, NCCL version 2.7.8
```
