### ISSUE TITLE
Multiprocessing_distributed issue

### ISSUE THREAD

**Issue by J-JunChen** [wbhu/BPNet#15]
Hey, @wbhu !

I would like to ask why the `train()` function in `train.py` doesn't  have  `dist.all_reduce` funciton but `validate()` has? 

the function like this in train.py as follows:

``` 
if args.multiprocessing_distributed:
    dist.all_reduce(intersection), dist.all_reduce(union), dist.all_reduce(target)
```

**Comment by wbhu** [comment]
Hi,

Thanks for your comment. Because we don't need very accurate metrics during the training time, so for efficiency, we didn't sync it.

**Comment by Jun-jieChen** [comment]
嗯嗯，我已经收到你的邮件啦~
