### ISSUE TITLE
Do you have estimated time for training on Scannet V2 from scratch?

### ISSUE THREAD

**Issue by yuchenlichuck** [wbhu/BPNet#16]
RT, we are focusing on the efficiency of 3d models, so we want to know how was the time performance for bpnet.
BTW, thanks for your talent work, it is fabulous

**Comment by wbhu** [comment]
Hi,

For the voxel size of 5cm, the training takes about 2 days on four V100 GPUs.

**Comment by yuchenlichuck** [comment]
Thanks a lot!
