### ISSUE TITLE
data structure

### ISSUE THREAD

**Issue by kxhit** [wbhu/BPNet#3]
Hi! Thanks for your great work and source code!

I tried to run the code but met several problems. I am confused about the data structure of scannet in this repo. As there is some pieces of code like 
```
for x in self.data_paths: 
    ps = glob(join(x[:-15].replace(split, '2D'), 'color', '*.jpg'))
```
Could you give a specific explanation for easily usage? Thanks a lot!

**Comment by wbhu** [comment]
Hi, this piece of code is to transform the 3D scene path into 2D path.

**Comment by kxhit** [comment]
Thanks for your quick reply!
So what's the data structure for 3D path and 2D path? It seems in 3D path there should be 'train' or 'val' directories containing scene*/*.pth. And in 2D path there should be 'scannetv2_images' directory containing scene*/color, scene*/depth, scene*/label and scene*/pose. What's the relative path between 2D and 3D? Thanks!

**Comment by wbhu** [comment]
The dataset folder should be like this:

`
ScanNet
    train
        scene****_**_vh_clean_2.pth
    val
        scene****_**_vh_clean_2.pth
    2D
        scene****_**
            color
            depth
            label
            pose
        
`

**Comment by kxhit** [comment]
Thanks! It works now.
