### ISSUE TITLE
Which parts of ScanNet V2 need to be downloaded?

### ISSUE THREAD

**Issue by cjyiiiing** [wbhu/BPNet#4]
Hi, 

the ScanNetV2  dataset is too large, so I only want to download the needed parts of this dataset. Are the file types that BPNet uses .sens/_vh_clean_2.ply/_vh_clean_2.labels.ply/_2d-label.zip, and e.g. run '`python download-scannet.py -o [directory in which to download] --type .sens`'? If not, could you tell me which parts of ScanNet V2 need to be downloaded? Thanks!

the entire valid file suffixes are:
```
<scanId>
|-- <scanId>.sens
    RGB-D sensor stream containing color frames, depth frames, camera poses and other data
|-- <scanId>_vh_clean.ply
    High quality reconstructed mesh
|-- <scanId>_vh_clean_2.ply
    Cleaned and decimated mesh for semantic annotations
|-- <scanId>_vh_clean_2.0.010000.segs.json
    Over-segmentation of annotation mesh
|-- <scanId>.aggregation.json, <scanId>_vh_clean.aggregation.json
    Aggregated instance-level semantic annotations on lo-res, hi-res meshes, respectively
|-- <scanId>_vh_clean_2.0.010000.segs.json, <scanId>_vh_clean.segs.json
    Over-segmentation of lo-res, hi-res meshes, respectively (referenced by aggregated semantic annotations)
|-- <scanId>_vh_clean_2.labels.ply
    Visualization of aggregated semantic segmentation; colored by nyu40 labels (see img/legend; ply property 'label' denotes the ScanNet label id)
|-- <scanId>_2d-label.zip
    Raw 2d projections of aggregated annotation labels as 16-bit pngs with ScanNet label ids
|-- <scanId>_2d-instance.zip
    Raw 2d projections of aggregated annotation instances as 8-bit pngs
|-- <scanId>_2d-label-filt.zip
    Filtered 2d projections of aggregated annotation labels as 16-bit pngs with ScanNet label ids
|-- <scanId>_2d-instance-filt.zip
    Filtered 2d projections of aggregated annotation instances as 8-bit pngs
```

**Comment by cjyiiiing** [comment]
> Hi,
> 
> the ScanNetV2 dataset is too large, so I only want to download the needed parts of this dataset. Are the file types that BPNet uses .sens/_vh_clean_2.ply/_vh_clean_2.labels.ply/_2d-label.zip? If not, could you tell me which parts of ScanNet V2 need to be downloaded? Thanks!
> 
> the entire valid file suffixes are:
> 
> > |-- .sens
> >     RGB-D sensor stream containing color frames, depth frames, camera poses and other data
> > |-- _vh_clean.ply
> >     High quality reconstructed mesh
> > |-- _vh_clean_2.ply
> >     Cleaned and decimated mesh for semantic annotations
> > |-- _vh_clean_2.0.010000.segs.json
> >     Over-segmentation of annotation mesh
> > |-- .aggregation.json, _vh_clean.aggregation.json
> >     Aggregated instance-level semantic annotations on lo-res, hi-res meshes, respectively
> > |-- _vh_clean_2.0.010000.segs.json, _vh_clean.segs.json
> >     Over-segmentation of lo-res, hi-res meshes, respectively (referenced by aggregated semantic annotations)
> > |-- _vh_clean_2.labels.ply
> >     Visualization of aggregated semantic segmentation; colored by nyu40 labels (see img/legend; ply property 'label' denotes the ScanNet label id)
> > |-- _2d-label.zip
> >     Raw 2d projections of aggregated annotation labels as 16-bit pngs with ScanNet label ids
> > |-- _2d-instance.zip
> >     Raw 2d projections of aggregated annotation instances as 8-bit pngs
> > |-- _2d-label-filt.zip
> >     Filtered 2d projections of aggregated annotation labels as 16-bit pngs with ScanNet label ids
> > |-- _2d-instance-filt.zip
> >     Filtered 2d projections of aggregated annotation instances as 8-bit pngs

**Comment by wbhu** [comment]
Besides the 3D data, we also used the .sens files, as they contain the 2D images.
