### ISSUE TITLE
About training time~

### ISSUE THREAD

**Issue by haibo-qiu** [wbhu/BPNet#7]
Hi,
What an excellent work!

You mentioned "We train our BPNet on the ScanNetV2 dataset for 100 epochs" in the paper.
And I am interested in the details about the 100 epochs training. For example, what backbone (e.g., ResNet34 from the config file), how many GPUs, what kind of GPUs (e.g., V100?), and the total training hours~

I would appreciate it very much if you can share these details~
Thanks~

**Comment by prograguo** [comment]
I also want to know，

**Comment by wbhu** [comment]
Hi,

We used UNet34 for both 2D and 3D sub-networks for the voxel size of 2cm, it took about 3 days to be trained on 4 RTX 6000 GPUs. For voxel size of 5cm, the training took about 1 day.

**Comment by haibo-qiu** [comment]
Thanks a lot!!
