### ISSUE TITLE
Your paper is excellent! but There are some points i can't understand.

### ISSUE THREAD

**Issue by demul** [wbhu/BPNet#8]
Your paper is excellent. The idea of BPM is beautiful. and Explanation about data structure of BPM is very kind and easy-to-understand. Thank you for your contribution to this field.

But after reading your paper, I still have some points which i can't understand, and I think if some explanations for these are provided, it will be great improvements for me, and for your paper as well!

First, I cannot understand the philosophy behind the method to get point cloud as input of the 3D network.
Why extract 3D point cloud from reconstructed 3D surface? Why don't you create point cloud from depth frame directly? 
Your said, "as done in [Mincowski Paper]".
But, Even after reading [Mincowski Paper], I cannot have any idea about why extract 3D point cloud from reconstructed 3D surface.
Can you explain it?

Second, I want to point out the ablation study with regard to the ablation for the number of 2D views.
The test on 2D mIoU is OK.
But, To the best of my understanding about your paper, The test result on 3D mIoU is very confusing.
Let me give a example situation.
If you have 1 scene and there are 5 views, And about 5 number of view result, It's OK. 
And then, About 4 views result, What's going on? Isn't there some Not-Evaluated part on that scene?
Or, To evaluate whole scene by 4 views method, There will be overlapped voxels inevitably. How to evaluate these overlaps fairly?

Third, There will be both overlapped area and non-overlapped area on ScanNet Dataset even after view sampling.
I think evaluating only on mixed(overlapped area and non-overlapped) parts is not a fully ablation.
I suggest you to give ablation result(2D/3D mIoU) only with 'overlapped parts', separately with mixed result.

Thank you.

**Comment by wbhu** [comment]
1. Depth map is view-dependent, while the point cloud extracted from the surface contains the information that is occluded in a certain viewpoint.
2. During the evaluation, we make sure all the images in the testset are evaluated no matter what the view number is. Please check the code for details.
3. Thanks for your suggestion. We will consider extending the experiments in the future.

**Comment by demul** [comment]
> * 
> * During the evaluation, we make sure all the images in the testset are evaluated no matter what the view number is. Please check the code for details.

Thanks for reply. I understand.
I had some misunderstanding about the scenario this model supposed to deal with.
The scenario i misunderstood was that
1. Do not have 3D shape already
2. Must build 3D shape from Multi-Views

But your scenario is actually that
1. Do have 3D shape already
2. Do not build 3D shape from Multi-Views



PS.
I test your model on my scenario and it seems work quite well especially when 3D shape is too dirty to be recognized only with 3D shape itself.
If you have plan to make more publication about BPNet-styled model, i suggest you emphasize its performance not only just on 'very clean benchmark data' but on 'dirty realworld data'(3D shapes  made from Multi-View). It's unique advantage of your model.

**Comment by wbhu** [comment]
Thanks for your valuable suggestions. Your provided scenario is worthy to further explore.
